import QtQuick
import QtQuick.Controls
Item {
    id:parent1
    Rectangle{
        id:main
        width:parent1.width/3
        height:parent1.height/2
        color:"blue"
        border.width:5
        border.color:"green"
        anchors{
            right:parent1.right
            bottom:parent1.bottom
        }
        Text{
            id:myText
            text:"My Text"
            font.pixelSize:10
            anchors{
              centerIn:parent
            }
        }
        radius:100
        Image {
            id: image
            source: "assets/deadpool.png"
            width:parent.width/3
            height:parent.width/3
            anchors{
                right:parent.right
            }
            MouseArea{
                anchors.fill:parent
                onClicked:{
                    myText.color="green"
                    myText.font.pixelSize=30
                    myText.text="HELLO"
                }
            }
        }
    }
    Row{
        width:parent1.width/3
        height:parent1.height/3
        spacing:5
        anchors.verticalCenter:parent1.verticalCenter
        Rectangle{
            width:parent.width/5
            height:parent.height
            color:"red"
        }
        Rectangle{
            width:parent.width/5
            height:parent.height
            color:"yellow"
        }
        Rectangle{
            width:parent.width/5
            height:parent.height
            color:"red"
        }
        Rectangle{
            width:parent.width/5
            height:parent.height
            color:"yellow"
        }
    }
    Column{
        width:parent.width/3
        height:parent.height/4
        spacing:5
          anchors{
             right:parent.right
             }
        Rectangle{
            width:parent.width
            height:parent.height/2
            color:"pink"
        }
        Rectangle{
            width:parent.width
            height:parent.height/2
            color:"black"
        }
        Rectangle{
            width:parent.width
            height:parent.height/2
            color:"pink"
        }
        Rectangle{
            width:parent.width
            height:parent.height/2
            color:"black"
        }
    }
    Button{
        anchors.centerIn:parent
        anchors.verticalCenter:parent.verticalCenter
        text:"click"
        width:100
        height:100
        onClicked:main.rotation=90
        background:Rectangle{
            width:100
            height:100
            color:"red"
            radius:100
        }
    }
}
